// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt-TeW16mOxQguUtYhWAeSmgFM-4jMGWw',
    appId: '1:111065804542:web:3f0d1e7fd43b3737187faf',
    messagingSenderId: '111065804542',
    projectId: 'weatherapp-2ca50',
    authDomain: 'weatherapp-2ca50.firebaseapp.com',
    storageBucket: 'weatherapp-2ca50.firebasestorage.app',
    measurementId: 'G-HEB5ZMX90C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCavOalrECzOttKc93x-kw2T5Dz8-H8-0Y',
    appId: '1:111065804542:android:7c8bd07a5630f9e7187faf',
    messagingSenderId: '111065804542',
    projectId: 'weatherapp-2ca50',
    storageBucket: 'weatherapp-2ca50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH1F3PdIb_3F8z8swE0PXM-DhLXjQJayI',
    appId: '1:111065804542:ios:fb17d11e7599cfaf187faf',
    messagingSenderId: '111065804542',
    projectId: 'weatherapp-2ca50',
    storageBucket: 'weatherapp-2ca50.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH1F3PdIb_3F8z8swE0PXM-DhLXjQJayI',
    appId: '1:111065804542:ios:fb17d11e7599cfaf187faf',
    messagingSenderId: '111065804542',
    projectId: 'weatherapp-2ca50',
    storageBucket: 'weatherapp-2ca50.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt-TeW16mOxQguUtYhWAeSmgFM-4jMGWw',
    appId: '1:111065804542:web:23cdf39bd98be89d187faf',
    messagingSenderId: '111065804542',
    projectId: 'weatherapp-2ca50',
    authDomain: 'weatherapp-2ca50.firebaseapp.com',
    storageBucket: 'weatherapp-2ca50.firebasestorage.app',
    measurementId: 'G-6CX7ERFY7G',
  );

}